apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  labels:
    app: api-server
spec:
  type: NodePort
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 2024
      targetPort: 2024
      nodePort: 30000
