apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:8.12.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
            - name: cluster.name
              value: elastic-cluster
            - name: bootstrap.memory_lock
              value: "true"
            - name: "ES_JAVA_OPTS"
              value: "-Xms512m -Xmx512m"
            - name: "xpack.security.enabled"
              value: "false"
            - name: "xpack.security.enrollment.enabled"
              value: "false"
          # volumeMounts:
          #   - mountPath: /usr/share/elasticsearch/data
          #     name: elasticsearch-data
          # resources:
          #   requests:
          #     memory: "512Mi"
          #     cpu: "1"
          #   limits:
          #     memory: "1Gi"
          #     cpu: "2"
    # volumes:
    #     - name: elasticsearch-data
    #       persistentVolumeClaim:
    #         claimName: elasticsearch-data
