apiVersion: v1
kind: Service
metadata:
  name: elastic-service
spec:
  selector:
    app: elasticsearch
  ports:
    - name: p1
      protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 30001
    - name: p2
      protocol: TCP
      port: 9300
      targetPort: 9300
      nodePort: 30002
  type: NodePort
